name: Go Docker CI/CD

on:
  push:
    branches: [ "master" ]

# Set permissions for the GitHub Token to allow pushing images
permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.7'
      - run: go test -v ./...



  build-and-push:
    needs: test # Only build the image if tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Tags the image as ghcr.io/username/repo-name:latest
          tags: ghcr.io/${{ github.repository }}:latest

#  deploy:
#    needs: build-and-push # Only deploy if the image was successfully pushed
#    runs-on: ubuntu-latest
#    steps:
#      - name: Deploy to Server via SSH
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            # 1. Login to GitHub Container Registry
#            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
#
#            # 2. Pull the latest image
#            docker pull ghcr.io/${{ github.repository }}:latest
#
#            # 3. Stop and remove the old container (if it exists)
#            docker stop my-go-app || true
#            docker rm my-go-app || true
#
#            # 4. Run the new container
#            docker run -d \
#              --name my-go-app \
#              -p 80:8080 \
#              --restart unless-stopped \
#              ghcr.io/${{ github.repository }}:latest